JAVA 3RD B 2022 CLASS
B
Stream
Classwork
People
JAVA 3RD B 2022 CLASS B
JAVA 3RD B 2022 CLASS
B
Upcoming
Woohoo, no work due soon!

Announce something to your class

Announcement: "Exception Slides and Programs."
Vikranth Bm
Created YesterdayYesterday
Exception Slides and Programs.

Exceptions.pptx
PowerPoint

exc1.java
Java

exc2.java
Java

exco.java
Java

MethNestTry.java
Java

MultiCatch.java
Java

Nesttry.java
Java

SuperSubCatch.java
Java

ThrowDemo.java
Java

ThrowsDemo1.java
Java

ThrowsDemo2.java
Java

ExceptionDemo.java
Java


Announcement: "Java Concepts Slides"
Vikranth Bm
Created Dec 22, 2022Dec 22, 2022
Java Concepts Slides

III SEM Object Oriented Java Programming-19CS3PCOOJ.pptx
PowerPoint

Java Introduction.pptx
PowerPoint


Announcement: "JAVA PROGRAMS"
Vikranth Bm
Created Dec 15, 2022Dec 15, 2022
JAVA PROGRAMS

ab.java
Java

abst.java
Java

abst1.java
Java

callcons.java
Java

Demo.java
Java

Demoboxsuper.java
Java

Demoboxweight1.java
Java

demop.java
Java

Dyn1.java
Java

Dyndispatch.java
Java

equalsDemo.java
Java

getscharstring.java
Java

overloaddemo.java
Java

simplein.java
Java

SimpleInheritance.java
Java

Testiface.java
Java

usesuper.java
Java

usesupermethod.java
Java

class MethNestTry{

               static void nesttry(int a) {
                
                 try{
               /*If one command Line argument is used,then a divide by zero exception 
              will be generated by the following code*/

                 if(a==1)  a=a/(a-a);

             /*If two command Line arguments are used then generate an Out of Bound Exception*/
 
                  if(a==2){
                             int c[]={1};
                               c[42]=99;
                             }
              }//end of try block in method

                 catch(ArrayIndexOutOfBoundsException e){
               System.out.println("Array Index out of Bound:"+e);
              }

         }
             
        public static void main(String args[]){

                    try{
                           int a=args.length;
      /* If no command Line args are present the following statement will generate a divide by zero exception */
                          int b=42/a;
                       System.out.println("a ="+a);
                        nesttry(a);
                       }
              catch(ArithmeticException e){
                    System.out.println("Divide by zero:"+e);
                  }

            System.out.println("After method Try catch statement");
           } 
        }



MethNestTry.java
Displaying MethNestTry.java.